version: "3.3"

services:
  backend:
    container_name: kupipodariday-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: compose-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    container_name: kupipodariday-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: compose-frontend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend

  postgres:
    container_name: app-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    container_name: kupipodariday-adminer
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
