version: "3.9"

services:
  backend:
    container_name: kupipodariday-api
    build:
      context: backend
      dockerfile: Dockerfile
    image: compose-backend
    ports:
      - 4000:3000
    env_file:
      - .env
  frontend:
    container_name: kupipodariday-front
    build:
      context: frontend
      dockerfile: Dockerfile
    image: compose-frontend
    ports:
      - 5001:80
    env_file:
      - .env
  postgres:
    container_name: app-postgress
    volumes:
      - postgres_data:/data/postgres
    image: postgres
    env_file:
      - .env
  adminer:
    container_name: kupipodariday-adminer
    image: adminer
    ports:
      - 8081:8080

    networks:
      backend:
      frontend:

volumes:
  postgres_data: